blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: FILE AN ISSUE OMG
    about: Can we actually pre-fill an issue with a project?
    url: https://github.com/polarweasel/actions-testing/issues/new?assignees=polarweasel&labels=enhancement%2C+question&title=A+pre-filled+title&projects=polarweasel/actions-testing/1%2Cpolarweasel/actions-testing/2&template=bugreport-form
