blank_issues_enabled: true
contact_links:
  - name: URL-based issue submission
    about: Create an issue using query parameters, defined in config.yml
    url: https://github.com/polarweasel/actions-testing/issues/new?assignees=polarweasel&labels=enhancement%2C+question&title=A+pre-filled+title&projects=polarweasel/actions-testing/1%2Cpolarweasel/actions-testing/2
