name: SDK version cron job

on:
  schedule:
    - cron: '*/5 * * * *'

#defaults:
#  run:
#    shell: bash

jobs:
  fetch_sdk_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get JS SDK version
      run: ./.github/scripts/check-js-sdk.sh

#    - name: Get Swift SDK version
#      shell: bash
#      run: ./.github/scripts/check-sdk.sh --sdk=swift
